# Generated by Django 2.0 on 2017-12-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171230_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='Main board', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('owner', 'name')},
        ),
    ]
