# Generated by Django 2.0 on 2017-12-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171230_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='board',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
