# Generated by Django 2.0 on 2017-12-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171230_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Profile'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Board'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Groceries', 'Groceries'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Kids', 'Kids'), ('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Eating out', 'Eating out'), ('Other', 'Other'), ('Salary', 'Salary')], max_length=50),
        ),
    ]
