# Generated by Django 2.0 on 2017-12-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20171231_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ['-date']},
        ),
    ]
