# Generated by Django 2.0 on 2017-12-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20171231_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
