# Generated by Django 2.0 on 2018-01-10 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20171231_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='cost_currency',
        ),
        migrations.AddField(
            model_name='board',
            name='currency',
            field=models.CharField(default='USD', max_length=30),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Bills', 'Bills'), ('Taxes', 'Taxes'), ('Clothes', 'Clothes'), ('Shopping', 'Shopping'), ('Holidays', 'Holidays'), ('Health', 'Health'), ('Sports', 'Sports'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Kids', 'Kids'), ('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Going out', 'Going out'), ('Eating out', 'Eating out'), ('Other', 'Other'), ('Salary', 'Salary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='spending',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='spending',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
